"""empty message

Revision ID: 1dc444699691
Revises: 5049011f7f9a
Create Date: 2014-11-26 14:19:03.987765

"""

# revision identifiers, used by Alembic.
revision = '1dc444699691'
down_revision = '5049011f7f9a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
