"""empty message

Revision ID: 29c38cfc4579
Revises: 166d771a2073
Create Date: 2014-12-23 11:37:46.782791

"""

# revision identifiers, used by Alembic.
revision = '29c38cfc4579'
down_revision = '166d771a2073'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=4000), nullable=True),
    sa.Column('area', sa.String(length=4000), nullable=True),
    sa.Column('city', sa.String(length=4000), nullable=True),
    sa.Column('state', sa.String(length=4000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'jobs', sa.Column('field_id', sa.Integer(), nullable=True))
    op.add_column(u'jobs', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.add_column(u'jobs', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'field', ['field_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'location', ['location_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'industry', ['industry_id'], ['id'])
    op.add_column(u'user', sa.Column('field_id', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('industry_id', sa.Integer(), nullable=True))
    op.add_column(u'user', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'industry', ['industry_id'], ['id'])
    op.create_foreign_key(None, 'user', 'location', ['location_id'], ['id'])
    op.create_foreign_key(None, 'user', 'field', ['field_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'location_id')
    op.drop_column(u'user', 'industry_id')
    op.drop_column(u'user', 'field_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column(u'jobs', 'location_id')
    op.drop_column(u'jobs', 'industry_id')
    op.drop_column(u'jobs', 'field_id')
    op.drop_table('location')
    op.drop_table('industry')
    op.drop_table('field')
    ### end Alembic commands ###
