"""empty message

Revision ID: 5049011f7f9a
Revises: None
Create Date: 2014-11-26 13:58:13.445228

"""

# revision identifiers, used by Alembic.
revision = '5049011f7f9a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
