"""empty message

Revision ID: 57b3461382b6
Revises: 17a8ddcd41c1
Create Date: 2014-11-29 14:02:24.160206

"""

# revision identifiers, used by Alembic.
revision = '57b3461382b6'
down_revision = '17a8ddcd41c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('skills', sa.String(length=4000), nullable=True),
    sa.Column('poster_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('expires', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    ### end Alembic commands ###
